name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout your code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH (No passphrase input)
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy code to the server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@74.208.194.227 << 'EOF'
        # Navigate to the project folder
        cd /var/www/html/node-demo-app

        # Pull latest changes
        git pull origin main

        # Install dependencies
        npm install

        # Restart the application (Assuming you're using PM2)
        pm2 restart all
        EOF
