name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to AWS
      run: |
        ssh root@${{ secrets.AWS_HOST }} '
          cd /var/www/html/node-demo-app &&
          git pull origin main &&
          npm install &&
          pm2 restart node-demo-app || pm2 start npm --name "node-demo-app" -- start
        '