name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@74.208.194.227 << 'EOF'
        # Navigate to the project folder
        cd /var/www/html/node-demo-app
        
        # Backup .env file
        cp .env .env.backup 2>/dev/null || :
        
        # Reset any local changes
        git fetch --all
        git reset --hard origin/main
        
        # Restore .env file
        cp .env.backup .env 2>/dev/null || :
        
        # Install dependencies
        npm install
        
        # Clean npm cache (optional, but can help with dependency issues)
        npm cache clean --force
        
        # Rebuild node modules
        rm -rf node_modules
        npm install
        
        # Restart the application
        pm2 restart 18;
        
        # Show status
        echo "Deployment completed"
        git status
        pm2 status
        EOF