name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@your-server.com '
            cd /var/www/html/node-demo-app &&
            git stash &&              # Stash local changes
            git reset --hard HEAD &&  # Reset any uncommitted changes
            git pull origin main &&   # Pull latest changes
            npm install &&            # Install dependencies
            pm2 restart all          # Restart your app
          '